CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(20)
);

INSERT INTO PRODUCT
VALUES ('NB_SS7', '»ï¼º³ëÆ®ºÏ', 1570000, '½Ã¸®Áî7');

INSERT INTO PRODUCT
VALUES ('NB_AMA4', '¸ÆºÏ¿¡¾î', 1200000, 'XCODE4');

INSERT INTO PRODUCT
VALUES ('PC_IBM', 'IBMPC', 750000, 'WINDOWS8');

COMMIT;

SELECT * FROM PRODUCT;
